post_install() {
    pkgname='gui-for-singbox'
    case ${LANG} in
    'zh_CN.UTF-8')
        printf "\033[1;31m请手动更改目录/opt/${pkgname}的所有者,所属组 \033[1;32mchown -R youUSER:youGROUP /opt/${pkgname}\033[0m\n"
        ;;
    *)
        printf "\033[1;31mPlease manually change the owner and group of the /opt/${pkgname} directory \033[1;32mchown -R youUSER:youGROUP /opt/${pkgname}\033[0m\n"
        ;;
    esac
}

post_upgrade() {
    post_install
}one
